name: 'Setup Git for Windows SDK'
description: 'Set up an environment to develop Git for Windows'
author: 'Johannes Schindelin'
branding:
  icon: fast-forward
  color: blue
inputs:
  flavor:
    required: false
    description: 'The subset (if any) of the SDK: minimal, makepkg-git, build-installers, or full'
    default: 'minimal'
  architecture:
    required: false
    description: 'The architecture of the SDK: x86_64 or i686'
    default: 'x86_64'
  msys:
    required: false
    description: 'Whether to start in MSYS mode (defaults to false)'
    default: 'false'
  path:
    required: false
    description: 'Where to write the SDK files'
    default: ''
  verbose:
    required: false
    description: 'Whether to log files as they are extracted'
    default: '250'
  cache:
    required: false
    description: 'Use @actions/cache to accelerate this Action'
    default: 'auto'
runs:
  using: 'node16'
  main: 'dist/index.js'
